const aromaticas = [
  {
    id: 1,
    producto: "Albahaca",
    codigo_de_barras: "#¡VALOR!",
    codigo: 4,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/ALBAHACA 16 AGOSTO 2023.webp",
  },
  {
    id: 2,
    producto: "Albahaca Violeta",
    codigo_de_barras: "#¡VALOR!",
    codigo: 5,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/ALBAHACA VIOLETA 2024.webp",
  },
  {
    id: 3,
    producto: "Apio",
    codigo_de_barras: "#¡VALOR!",
    codigo: 10,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/APIO 19 ENERO 2021.webp",
  },
  {
    id: 4,
    producto: "Cilantro",
    codigo_de_barras: "#¡VALOR!",
    codigo: 65,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/CILANTRO ENERO 2024.webp",
  },
  {
    id: 5,
    producto: "Eneldo",
    codigo_de_barras: "#¡VALOR!",
    codigo: 95,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/ENELDO DIC 2020.webp",
  },
  {
    id: 6,
    producto: "Hinojo",
    codigo_de_barras: "#¡VALOR!",
    codigo: 162,
    precio: 30.0,
    imagen: "../assets/categorias/aromaticas/HINOJO ENERO 2024.webp",
  },
  {
    id: 7,
    producto: "Manzanilla",
    codigo_de_barras: "#¡VALOR!",
    codigo: 32,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/MANZANILLA 13OCT2022.webp",
  },
  {
    id: 8,
    producto: "Melissa",
    codigo_de_barras: "#¡VALOR!",
    codigo: 183,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/MELISSA 13 OCTUBRE 2022.webp",
  },
  {
    id: 9,
    producto: "Menta",
    codigo_de_barras: "#¡VALOR!",
    codigo: 186,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/MENTA 16 AGOSTO 2023.webp",
  },
  {
    id: 10,
    producto: "Mix de plantas aromaticas",
    codigo_de_barras: "#¡VALOR!",
    codigo: 410,
    precio: 37.0,
    imagen: "../assets/categorias/aromaticas/MIX DE PLANTAS AROMATICAS.webp",
  },
  {
    id: 11,
    producto: "Mix de plantas para infusiones",
    codigo_de_barras: "#¡VALOR!",
    codigo: 408,
    precio: 37.0,
    imagen:
      "../assets/categorias/aromaticas/MIX DE PLANTAS PARA INFUSIONES.webp",
  },
  {
    id: 12,
    producto: "Oregano",
    codigo_de_barras: "#¡VALOR!",
    codigo: 194,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/OREGANO ENERO 2024.webp",
  },
  {
    id: 13,
    producto: "Perejil",
    codigo_de_barras: "#¡VALOR!",
    codigo: 207,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/PEREJIL 05JUNIO2023.webp",
  },
  {
    id: 14,
    producto: "Romero",
    codigo_de_barras: "#¡VALOR!",
    codigo: 263,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/ROMERO MARZO 2023.webp",
  },
  {
    id: 15,
    producto: "Tomillo",
    codigo_de_barras: "#¡VALOR!",
    codigo: 275,
    precio: 22.0,
    imagen: "../assets/categorias/aromaticas/TOMILLO 01MARZO2024.webp",
  },
];
