const hortalizas = [
  {
    id: 1,
    producto: "Acelga",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 1,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/ACELGA MAYO 2020.webp",
  },
  {
    id: 2,
    producto: "Alcachofa",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 6,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/ALCACHOFA 30 MARZO 2022.webp",
  },
  {
    id: 3,
    producto: "Amaranto",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 386,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/AMARANTO 05102015.webp",
  },
  {
    id: 4,
    producto: "Arugula",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 368,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/ARUGULA 19 OCTUBRE 2021.webp",
  },
  {
    id: 5,
    producto: "Berenjena",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 16,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/BERENJENA 14062016.webp",
  },
  {
    id: 6,
    producto: "Berro de Agua",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 17,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/BERRO DE AGUA DIC 2020.webp",
  },
  {
    id: 7,
    producto: "Brocoli",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 372,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/BROCOLI 30 MARZO 2022.webp",
  },
  {
    id: 8,
    producto: "Calabacin",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 20,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/CALABACIN 16 AGOSTO 2023.webp",
  },
  {
    id: 9,
    producto: "Cebolla blanca",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 34,
    precio: 30.0,
    imagen:
      "../assets/categorias/hortalizas/CEBOLLA BLANCA 16 AGOSTO 2023.webp",
  },
  {
    id: 10,
    producto: "Cebolla Roja",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 42,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/CEBOLLA ROJA 05 MAYO 2022.webp",
  },
  {
    id: 11,
    producto: "Cebollin",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 46,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/CEBOLLIN 01MARZO2024.webp",
  },
  {
    id: 12,
    producto: "Chile Jalapeño",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 55,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/JALAPEÑO 5JUNIO2023.webp",
  },
  {
    id: 13,
    producto: "Chile Peperone Picante-CAYENNE",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 60,
    precio: 22.0,
    imagen:
      "../assets/categorias/hortalizas/CHILE CAYENNE 13 OCTUBRE 2022.webp",
  },
  {
    id: 14,
    producto: "Chile Pimiento Corto",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 216,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/PIMIENTO CORTO 2 OCT 2023.webp",
  },
  {
    id: 15,
    producto: "Chile Pimiento Largo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 222,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/PIMIENTO LARGO ENERO 2024.webp",
  },
  {
    id: 16,
    producto: "Chile Sigarreta",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 62,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/CHILE SIGARRETA.webp",
  },
  {
    id: 17,
    producto: "Chipilin",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 385,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/CHIPILIN 13 OCTUBRE 2022.webp",
  },
  {
    id: 18,
    producto: "Col de Bruselas",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 81,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/COL DE BRUSELAS SEPT 2020.webp",
  },
  {
    id: 19,
    producto: "Col de Milan",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 80,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/COL.webp",
  },
  {
    id: 20,
    producto: "Coliflor",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 84,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/COLIFLOR 2024.webp",
  },
  {
    id: 21,
    producto: "Esparrago",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 98,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/ESPARRAGO 13 OCTUBRE 2022.webp",
  },
  {
    id: 22,
    producto: "Espinaca",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 100,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/ESPINACA MARZO 2023.webp",
  },
  {
    id: 23,
    producto: "Fresa",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 129,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/FRESA 16 AGOSTO 2023.webp",
  },
  {
    id: 24,
    producto: "Frijol Ejotero",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 276,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/EJOTE FEBRERO 2023.webp",
  },
  {
    id: 25,
    producto: "Guisante",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 145,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/GUISANTE 19 ENERO 2021.webp",
  },
  {
    id: 26,
    producto: "Haba",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 152,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/HABA.webp",
  },
  {
    id: 27,
    producto: "Hierbamora",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 161,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/HIERBAMORA ENERO 2024.webp",
  },
  {
    id: 28,
    producto: "Jamaica",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 388,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/JAMAICA ENERO 2024.webp",
  },
  {
    id: 29,
    producto: "Lechuga",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 171,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/LECHUGA 13 OCTUBRE 2022.webp",
  },
  {
    id: 30,
    producto: "Lechuga Roja",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 176,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/LECHUGA ROJA 19JULIO2021.webp",
  },
  {
    id: 31,
    producto: "Lechuga Romana",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 166,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/LECHUGA ROMANA 29JUNIO 2022.webp",
  },
  {
    id: 32,
    producto: "Maiz Dulce",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 179,
    precio: 37.0,
    imagen: "../assets/categorias/hortalizas/MAIZ DULCE 9 ABRIL 2021.webp",
  },
  {
    id: 33,
    producto: "Melon",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 184,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/MELON 18AGOSTO 2022.webp",
  },
  {
    id: 34,
    producto: "Mezcla de Ensaladas",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 188,
    precio: 22.0,
    imagen:
      "../assets/categorias/hortalizas/MEZCLA DE ENSALADAS 29JUNIO 2022.webp",
  },
  {
    id: 35,
    producto: "Mezcla de Hierbas p/C",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 189,
    precio: 22.0,
    imagen:
      "../assets/categorias/hortalizas/MEZCLA DE HIERBAS PARA COCINAR.webp",
  },
  {
    id: 36,
    producto: "Miltomate",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 274,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/MILTOMATE 18AGOSTO 2022.webp",
  },
  {
    id: 37,
    producto: "Mix de hortalizas para semilleros",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 407,
    precio: 37.0,
    imagen:
      "../assets/categorias/hortalizas/MEZCLA DE HORTALIZAS PARA SEMILLEROS.webp",
  },
  {
    id: 38,
    producto: "Mix de hortalizas para siembra directa",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 409,
    precio: 37.0,
    imagen:
      "../assets/categorias/hortalizas/MEZCLA DE SEMILLAS PARA SIEMBRA DIRECTA ENERO 2024.webp",
  },
  {
    id: 39,
    producto: "Mix de plantas para chirmol/Salsa Roja",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 412,
    precio: 37.0,
    imagen: "../assets/categorias/hortalizas/MEZCLA SALSA ROJA.webp",
  },
  {
    id: 40,
    producto: "Mix de Plantas para chirmol/Salsa Verde",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 413,
    precio: 37.0,
    imagen: "../assets/categorias/hortalizas/MEZCLA SALSA VERDE.webp",
  },
  {
    id: 41,
    producto: "Mix de plantas para salsa picante",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 411,
    precio: 37.0,
    imagen: "../assets/categorias/hortalizas/MEZCLA DE SALSA PICANTE.webp",
  },
  {
    id: 42,
    producto: "Mostaza",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 369,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/MOSTAZA.webp",
  },
  {
    id: 43,
    producto: "Nabo Blanco",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 192,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/NABO SEPT 2020.webp",
  },
  {
    id: 44,
    producto: "Okra",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 193,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/OKRA.webp",
  },
  {
    id: 45,
    producto: "Pepino",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 202,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/PEPINO MARZO 2 2021.webp",
  },
  {
    id: 46,
    producto: "Puerro",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 228,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/PUERRO ENERO 2024.webp",
  },
  {
    id: 47,
    producto: "Rabano",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 233,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/RABANO ENERO 2024.webp",
  },
  {
    id: 48,
    producto: "Remolacha",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 252,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/REMOLACHA 9 ABRIL 2021.webp",
  },
  {
    id: 49,
    producto: "Repollo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 257,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/REPOLLO 29JUNIO 2022.webp",
  },
  {
    id: 50,
    producto: "Repollo Rojo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 262,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/REPOLLO ROJO.webp",
  },
  {
    id: 51,
    producto: "Sandia Larga",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 268,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/SANDIA LARGA FEBRERO 2023.webp",
  },
  {
    id: 52,
    producto: "Sandia Redonda",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 267,
    precio: 22.0,
    imagen:
      "../assets/categorias/hortalizas/SANDIA CRIMSON SWEET FEBRERO 2023.webp",
  },
  {
    id: 53,
    producto: "Tomate Largo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 272,
    precio: 30.0,
    imagen: "../assets/categorias/hortalizas/TOMATE LARGO ENERO 2024.webp",
  },
  {
    id: 54,
    producto: "Tomate Redondo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 271,
    precio: 37.0,
    imagen: "../assets/categorias/hortalizas/TOMATE REDONDO 5JUNIO2023.webp",
  },
  {
    id: 55,
    producto: "Zanahoria Berlicum",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 286,
    precio: 22.0,
    imagen: "../assets/categorias/hortalizas/ZANAHORIA 2 OCT 2023.webp",
  },
];
