const ornamentales = [
  {
    id: 1,
    producto: "Aleli",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 8,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ALELI 13 OCTUBRE 2022.webp",
  },
  {
    id: 2,
    producto: "Antirrino",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 9,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ANTIRRINO SEPT 2020.webp",
  },
  {
    id: 3,
    producto: "Cactus",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 19,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CACTUS 13 OCTUBRE 2022.webp",
  },
  {
    id: 4,
    producto: "Calendula",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 30,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CALENDULA 19 ENERO 2021.webp",
  },
  {
    id: 5,
    producto: "Campanula",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 31,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CAMPANULA 19JULIO2021.webp",
  },
  {
    id: 6,
    producto: "Capuchina",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 33,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CAPUCHINA 29JUNIO 2022.webp",
  },
  {
    id: 7,
    producto: "Celosia Plumosa",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 52,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/CELOSIA PLUMOSA 19 ENERO 2021.webp",
  },
  {
    id: 8,
    producto: "Centaurea",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 53,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CENTAUREA JUNIO 2020.webp",
  },
  {
    id: 9,
    producto: "Cipress Piramidal",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 429,
    precio: 37.0,
    imagen:
      "../assets/categorias/ornamentales/CIPRES PIRAMIDAL 24 ABRIL 2023.webp",
  },
  {
    id: 10,
    producto: "Clavel Amarillo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 72,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CLAVEL AMARILLO.webp",
  },
  {
    id: 11,
    producto: "Clavel Blanco",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 73,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/CLAVEL BLANCO 13 OCTUBRE 2022.webp",
  },
  {
    id: 12,
    producto: "Clavel Mix Claro",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 76,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/CLAVEL MIX CLARO 27 FEB 2019.webp",
  },
  {
    id: 13,
    producto: "Clavel Mix Oscuro",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 77,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/CLAVEL MIX OSCURO 05 MAYO 2022.webp",
  },
  {
    id: 14,
    producto: "Clavel Rojo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 78,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CLAVEL ROJO MARZO 2023.webp",
  },
  {
    id: 15,
    producto: "Coleus Variados",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 83,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/COLEUS DIC 2020.webp",
  },
  {
    id: 16,
    producto: "Cosmos variados",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 91,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/COSMOS VARIADOS 18AGOSTO 2022.webp",
  },
  {
    id: 17,
    producto: "Crisantemo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 92,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/CRISANTEMO 18AGOSTO 2022.webp",
  },
  {
    id: 18,
    producto: "Delphinium",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 93,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/DELPHINIUM ENERO 2024.webp",
  },
  {
    id: 19,
    producto: "Digital",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 94,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/DIGITAL 18AGOSTO 2022.webp",
  },
  {
    id: 20,
    producto: "Estatice Amarillo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 105,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ESTATICE AMARILLA.webp",
  },
  {
    id: 21,
    producto: "Estatice Azul",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 108,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ESTATICE AZUL.webp",
  },
  {
    id: 22,
    producto: "Estatice Blanco",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 111,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ESTATICE BLANCA.webp",
  },
  {
    id: 23,
    producto: "Estatice Mix",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 114,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ESTATICE MIX.webp",
  },
  {
    id: 24,
    producto: "Estatice Rojo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 120,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ESTATICE ROJA 05 MAYO 2022.webp",
  },
  {
    id: 25,
    producto: "Estrelicia",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 126,
    precio: 37.0,
    imagen: "../assets/categorias/ornamentales/ESTRELICIA 18AGOSTO 2022.webp",
  },
  {
    id: 26,
    producto: "Flores Anuales",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 127,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/FLORES ANUALES 29JUNIO 2022.webp",
  },
  {
    id: 27,
    producto: "Flox",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 128,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/FLOX 29 AGOSTO 2019.webp",
  },
  {
    id: 28,
    producto: "Gerbera",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 131,
    precio: 37.0,
    imagen: "../assets/categorias/ornamentales/GERBERA 13 OCTUBRE 2022.webp",
  },
  {
    id: 29,
    producto: "Gipsophilia",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 132,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/GIPSOPHILIA.webp",
  },
  {
    id: 30,
    producto: "Girasol",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 142,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/GIRASOL ENERO 2024.webp",
  },
  {
    id: 31,
    producto: "Girasol de Centro",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 143,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/GIRASOL DE CENTRO.webp",
  },
  {
    id: 32,
    producto: "Guisantes de Olor",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 151,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/GUISANTES DE OLOR DIC 2020.webp",
  },
  {
    id: 33,
    producto: "Ipomea V",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 164,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/IPOMEA VARIADA.webp",
  },
  {
    id: 34,
    producto: "Margarita botoncitos",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 180,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/MARGARITA BOTONCITOS.webp",
  },
  {
    id: 35,
    producto: "Margarita Gigante",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 181,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/MARGARITA GIGANTE 5JUNIO2023.webp",
  },
  {
    id: 36,
    producto: "Miosotis de los Alpes",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 190,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/MIOSOTIS 18AGOSTO 2022.webp",
  },
  {
    id: 37,
    producto: "Miramelindo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 191,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/MIRAMELINDO 18AGOSTO 2022.webp",
  },
  {
    id: 38,
    producto: "Mix de flores para abejas y otros insectos beneficos",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 406,
    precio: 37.0,
    imagen:
      "../assets/categorias/ornamentales/MEZCLA DE FLORES PARA ABEJAS.webp",
  },
  {
    id: 39,
    producto: "Pensamiento Amarillo",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 196,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/PENSAMIENTO AMARILLO 30 MARZO 2022.webp",
  },
  {
    id: 40,
    producto: "Pensamiento Azul",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 197,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/PENSAMIENTO AZUL 29JUNIO 2022.webp",
  },
  {
    id: 41,
    producto: "Pensamiento Mix",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 200,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/PENSAMIENTO MIX.webp",
  },
  {
    id: 42,
    producto: "Petunia Colgante",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 212,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/PETUNIA COLGANTE 03 DICIEMBRE 2021.webp",
  },
  {
    id: 43,
    producto: "Petunia Grande",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 213,
    precio: 37.0,
    imagen:
      "../assets/categorias/ornamentales/PETUNIA GRANDE 29JUNIO 2022.webp",
  },
  {
    id: 44,
    producto: "Petunia Grandiflora",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 214,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/PETUNIA GRANDIFLORA 02 JUNIO 2021.webp",
  },
  {
    id: 45,
    producto: "Pimiento Ornamental",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 221,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/PIMIENTO ORNAMENTAL DIC 2020.webp",
  },
  {
    id: 46,
    producto: "Reina Marg. Belleza",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 243,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/REINA MARGARITA BELLEZA 29JUNIO 2022.webp",
  },
  {
    id: 47,
    producto: "Reina Marg. Mix",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 241,
    precio: 22.0,
    imagen:
      "../assets/categorias/ornamentales/REINA MARGARITA MIX 29JUNIO 2022.webp",
  },
  {
    id: 48,
    producto: "Siempreviva",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 270,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/SIEMPREVIVA.webp",
  },
  {
    id: 49,
    producto: "Thuja",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 430,
    precio: 37.0,
    imagen: "../assets/categorias/ornamentales/THUJA 24 ABRIL 2023.webp",
  },
  {
    id: 50,
    producto: "Verdolaga",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 284,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/VERDOLAGA 05 MAYO 2022.webp",
  },
  {
    id: 51,
    producto: "Violeta",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 285,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/VIOLETA MARZO 2023.webp",
  },
  {
    id: 52,
    producto: "Zinnia",
    codigo_de_barras: "#¡DESCONOCIDO!",
    codigo: 291,
    precio: 22.0,
    imagen: "../assets/categorias/ornamentales/ZINNIA MARZO 2023.webp",
  },
];
